services:
    app:
        container_name: aplication
        build: 
            context: .
        ports:
            - "80:80"
        volumes:
            - "./:/var/www/html"
    db:
        container_name: database
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: Test-Buzzvel
        ports:
            - "3308:3306"
