services:
    app:
        container_name: aplication
        build: .
        restart: always
        ports:
            - "80:80"
        volumes:
            - ".:/var/www/html"
    db:
        container_name: database
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - "3006:3006"
