services:
    app:
        container_name: aplication
        build: .
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ".:/var/www/html"
    db:
        container_name: aplication
        image: mariadb:11.5.1
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - "3006:3006"
