services:
    app:
        container_name: aplication
        build: .
        restart: always
        ports:
            - "8000:80"
        volumes:
            - "/home/www/Back-End-Developer-Test-Buzzvel:/var/www/html"
    db:
        container_name: aplication
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - "3006:3006"
